FORMAT: 1A

# OnTrack

Teams OnTrack

## User [/user/{user_id}]

User Dashboard
For now just the graphic showing Constructor rates throught time.


### List all rates [GET]

+ Response 200 (application/json)

        [
            {
                "user_id": user_id
                "rates": [
                    {
                        "rated_at": "2015-08-05T08:40:51.620Z",
                        "constructors": [
                            { 
                                 "name": "Energy",
                                 "rate": 7
                            },
                            { 
                                 "name": "Focus",
                                 "rate": 8
                            },
                            { 
                                 "name": "Happiness",
                                 "rate": 9
                            },
                            { 
                                 "name": "Productivity",
                                 "rate": 7
                            }
                        ]
                    },
                    {
                        "rated_at": "2015-08-06T08:35:51.620Z",
                        "constructors": [
                            { 
                                 "name": "Energy",
                                 "rate": 8
                            },
                            { 
                                 "name": "Focus",
                                 "rate": 9
                            },
                            { 
                                 "name": "Happiness",
                                 "rate": 9
                            },
                            { 
                                 "name": "Productivity",
                                 "rate": 7
                            }
                        ]
                    },
                    {
                        "rated_at": "2015-08-07T08:50:51.620Z",
                        "constructors": [
                            { 
                                 "name": "Energy",
                                 "rate": 6
                            },
                            { 
                                 "name": "Focus",
                                 "rate": 5
                            },
                            { 
                                 "name": "Happiness",
                                 "rate": 7
                            },
                            { 
                                 "name": "Productivity",
                                 "rate": 6
                            }
                        ]
                    }
            
                ]
            }
        ]
        



###  Contructor [/user/constructor/{constructor_name}]
+ Parameters
    + constructor_name (enum[string])
        Name of the Contructor.
    
        + Members
            + 'Energy'
            + 'Happiness'
            + 'Focus'
            + 'Productivity'
    
### Constructors [GET]

+ Response 200 (application/json)

        [
            {
                "constructor": Energy,
                "rated_at": "2015-08-05T08:40:51.620Z",
                "rate": 7
                 
            }
            
        ]
        
#### Daily Rate Contructor [POST]

Rate your contructors and store them on DB.
It takes a JSON object containing a contructor's identifyied by string constructor, the time of the rating as rated_at and a rate between MIN_RATE and MAX_RATE.
        
+ Request (application/json)

        {
            "constructor": "Energy",
            "rated_at": "2015-08-05T08:40:51.620Z",
            "rate": 7
        }
        
+ Response 201 (application/json)

    + Body

            {
                "contructor": Energy,
                "rated_at": "2015-08-05T08:40:51.620Z",
                "rate": 7
            }